name: Update Virglrenderer Spec

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:  # Allow manual triggering

jobs:
  check-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
      
      - name: Check for changes in mesa-git
        id: check-mesa
        run: |
          # Get the latest commit hash from mesa-git
          LATEST_MESA_COMMIT=$(curl -s "https://api.github.com/repos/danayer/mesa-git/commits/main" | jq -r .sha)
          echo "Latest mesa-git commit: $LATEST_MESA_COMMIT"
          
          # Store the commit hash in a file if it doesn't exist
          if [ ! -f ".last_mesa_commit" ]; then
            echo $LATEST_MESA_COMMIT > .last_mesa_commit
            echo "First run, storing current commit"
            echo "changed=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          LAST_MESA_COMMIT=$(cat .last_mesa_commit)
          echo "Previous mesa-git commit: $LAST_MESA_COMMIT"
          
          if [ "$LATEST_MESA_COMMIT" != "$LAST_MESA_COMMIT" ]; then
            echo "Changes detected in mesa-git"
            echo $LATEST_MESA_COMMIT > .last_mesa_commit
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "No changes in mesa-git"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Update virglrenderer spec file
        if: steps.check-mesa.outputs.changed == 'true'
        run: |
          # Get the latest commit from virglrenderer
          LATEST_VIRGL_COMMIT=$(curl -s "https://gitlab.freedesktop.org/api/v4/projects/577/repository/commits" | jq -r '.[0].id')
          VIRGL_SHORT_COMMIT=${LATEST_VIRGL_COMMIT:0:8}
          echo "Latest virglrenderer commit: $VIRGL_SHORT_COMMIT"
          
          # Get current date in YYYYMMDD format
          CURRENT_DATE=$(date '+%Y%m%d')
          
          # Read current version from spec file
          CURRENT_VERSION=$(grep -oP '^Version:\s*\K[0-9.]+' /home/danayer/Загрузки/virglrenderer.spec)
          echo "Current version: $CURRENT_VERSION"
          
          # Parse the version and increment the last part
          BASE_VERSION=$(echo $CURRENT_VERSION | grep -oP '^[0-9]+\.[0-9]+\.')
          LAST_PART=$(echo $CURRENT_VERSION | grep -oP '[0-9]+$')
          NEW_LAST_PART=$((LAST_PART + 1))
          NEW_VERSION="${BASE_VERSION}${NEW_LAST_PART}"
          
          echo "New version: $NEW_VERSION"
          
          # Update the spec file
          sed -i "s/^Version:.*$/Version:	$NEW_VERSION/" /home/danayer/Загрузки/virglrenderer.spec
          sed -i "s|^Source:.*$|Source:         https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/$LATEST_VIRGL_COMMIT/virglrenderer-$LATEST_VIRGL_COMMIT.tar.bz2|" /home/danayer/Загрузки/virglrenderer.spec
          
          # Add new changelog entry
          CHANGELOG_ENTRY="* $(date '+%a %b %d %Y') Automated Update <github-actions@github.com> - $NEW_VERSION-1.git$VIRGL_SHORT_COMMIT\n- Automated update based on changes in mesa-git\n- Using latest virglrenderer commit $LATEST_VIRGL_COMMIT"
          sed -i "/^%changelog/a $CHANGELOG_ENTRY" /home/danayer/Загрузки/virglrenderer.spec
      
      - name: Commit and push changes
        if: steps.check-mesa.outputs.changed == 'true'
        run: |
          git add /home/danayer/Загрузки/virglrenderer.spec .last_mesa_commit
          git commit -m "Update virglrenderer to latest commit based on mesa-git changes"
          git push
